spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
    open-in-view: false
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      file: guess-the-word/compose.yaml
server:
  shutdown: graceful
