on:
  workflow_dispatch:
    inputs:
      project:
        description: "The project name. Specify the project relative to the root project."
        required: true
        type: choice
        options:
          - pto-scheduler
          - guess-the-word
          - kotlinx-serialization-ber
          - free-dsl

permissions: {}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Activate mise
        run: |
          mise env -D >> $GITHUB_ENV
      - uses: gradle/actions/setup-gradle@v4
      - name: Create release
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.MAVEN_CENTRAL_USERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.MAVEN_CENTRAL_TOKEN}}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.GPG_ARMORED_KEY}}
        run: ./gradlew :${{inputs.project}}:releaseCI --no-configuration-cache
