on:
  push:
    branches:
      - main
permissions: { }

env:
  JAVA_VERSION: 21

jobs:
  build-project:
    uses: ./.github/workflows/build_project.yml
    with:
      java-version: ${{ env.JAVA_VERSION }}
    secrets:
      inherit: true
    permissions:
      security-events: write

  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
    permissions:
      contents: write
