on:
  push:
    branches:
      - main
permissions: {}

jobs:
  build-project:
    uses: ./.github/workflows/build_project.yml
    secrets: inherit
    permissions:
      security-events: write

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - uses: actions/checkout@v5
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Super-Linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your fix mode variables to true
          FIX_JSON_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          FILTER_REGEX_EXCLUDE: .*CHANGELOG.md|.*gradlew.* # Ignore generated files
          VALIDATE_JSCPD: false # Disable JSCPD validation

  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
    permissions:
      contents: write
