on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions: { }

jobs:
  build-project:
    uses: ./.github/workflows/build_project.yml
    secrets: inherit
    permissions:
      security-events: write

  verify-gradle-wrapper:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

  review-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ vars.JAVA_VERSION }}
      - name: Perform dependency review
        uses: actions/dependency-review-action@v4
        continue-on-error: true
        with:
          retry-on-snapshot-warnings: true
    permissions:
      contents: write

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
            app_id: ${{ secrets.TACASCER_BOT_APP_ID }}
            private_key: ${{ secrets.TACASCER_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          token: ${{ steps.create_token.outputs.token }}
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your fix mode variables to true
          FIX_JSON_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          FILTER_REGEX_EXCLUDE: .*CHANGELOG.md|.*gradlew.* # Ignore generated files
          VALIDATE_JSCPD: false # Disable JSCPD validation
      - name: Import GPG Key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.TACASCER_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.TACASCER_BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit and push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix linting issues"
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
