on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions: { }

env:
  JAVA_VERSION: 21

jobs:
  build-project:
    uses: ./.github/workflows/build_project.yml
    with:
      java-version: ${{ env.JAVA_VERSION }}
    secrets:
      inherit: true
    permissions:
      security-events: write

  verify-gradle-wrapper:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

  review-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: Perform dependency review
        uses: actions/dependency-review-action@v4
        continue-on-error: true
        with:
          retry-on-snapshot-warnings: true
    permissions:
      contents: write

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Set your fix mode variables to true
          FIX_JSON_PRETTIER: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
          FILTER_REGEX_EXCLUDE: .*CHANGELOG.md|.*gradlew.* # Ignore generated files
          VALIDATE_JSCPD: false # Disable JSCPD validation
      - name: Commit and push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix linting issues"
